version: '3.8'
services:
  app:
    build: ./app
    container_name: web_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mynet

  mongo:
    image: mongo:5.0
    container_name: mongo_db
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynet

networks:
  mynet:

volumes:
  mongodata:
